# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# For Atom Feed & Site conf
domain: devconf.cz
author: DevConf.cz
email: EMAIL_HERE@devconf.cz
title: DevConf.cz

description: > # this means to ignore newlines until "baseurl:"
  DevConf.cz conference website

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devconf.cz" # the base hostname & protocol for your site
twitter_username: devconf_cz
#github_username:  devconf

# YAML defaults for pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# GitHub builds with safe mode, so enable it for previewing locally too
safe: true

# Don't compile these files/dirs into the website
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin

include:
  - _stylesheets
  - _javascript
  - assets/site.js
  - assets/vendor/jquery/dist/
  - assets/vendor/jquery.easing/js/
  - assets/vendor/bootstrap-sass/assets/javascripts/

sass:
  sass_dir: assets/
  style: :compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

# Let the following Jekyll plugins work in safemode
# (mimicing GitHub's config)
whitelist:
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-github-metadata

lang: en
